os:   linux
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


language: python
python: 3.7

before_install:
  - eval "${MATRIX_EVAL}"
  # make all travis scripts executable
  - sudo chmod u+x .travis/*.sh
  # upgrade pip
  - pip3 install --upgrade pip
  # install snakemake
  - pip3 install snakemake
  # install singularity
  - /bin/bash .travis/install_singularity.sh

script:
  - singularity version
