FROM rocker/verse:latest

MAINTAINER Kevin Kunzmann kevin.kunzmann@mrc-bsu.cam.ac.uk

# update apt
RUN sudo apt-get update

# install required R packages
RUN R -e "install.packages('rticulate')"

# install python
RUN sudo apt-get install -y python3-pip python3-dev python3-tk
RUN sudo pip3 install -U pip
RUN sudo pip3 install -U pandas numpy matplotlib
